#===============================================================================
# Skip_to_print makefile
# Author: Chris Wozniak
# CPSC525
#
# makefile for the second iteration of the ptrace solution to question 3
# assignment 1.
#
#===============================================================================
objects = my_mod.c

exploit: $(objects)
	gcc $(objects) -o exploit

clean:
	rm exploit
